# CokeFreestyleRandomizer.py
# Helps you decide what to order at your local Coca-Cola Freestyle

import random
import pdb

soda = [
    "Coca Cola",
    "Coca Cola Cherry",
    "Coca Cola Cherry Vanilla",
    "Coca Cola Lemon",
    "Coca Cola Lime",
    "Coca Cola Orange",
    "Coca Cola Raspberry",
    "Coca Cola Vanilla",
    "Coca Cola Orange Vanilla",
    "Diet Coke",
    "Diet Coke Cherry",
    "Diet Coke Cherry Vanilla",
    "Diet Coke Lemon",
    "Diet Coke Orange",
    "Diet Coke Raspberry",
    "Diet Coke Vanilla",
    "Diet Coke Ginger Lemon",
    "Diet Coke Ginger Lime",
    "Coke Zero",
    "Coke Zero Cherry",
    "Coke Zero Cherry Vanilla",
    "Coke Zero Lemon",
    "Coke Zero Lime",
    "Coke Zero Orange",
    "Coke Zero Raspberry",
    "Coke Zero Vanilla",
    "Coke Zero Orange Vanilla",
    "Caffeine Free Diet Coke",
    "Caffeine Free Diet Coke Cherry",
    "Caffeine Free Diet Coke Cherry Vanilla",
    "Caffeine Free Diet Coke Orange",
    "Caffeine Free Diet Coke Raspberry",
    "Caffeine Free Diet Coke Vanilla",
    "Caffeine Free Diet Coke Ginger Lime",
    "Caffeine Free Diet Coke Ginger Lemon",
    "Sprite",
    "Sprite Cherry",
    "Sprite Grape",
    "Sprite Orange",
    "Sprite Peach",
    "Sprite Raspberry",
    "Sprite Strawberry",
    "Sprite Vanilla",
    "Sprite Zero Sugar",
    "Sprite Zero Sugar Cherry",
    "Sprite Zero Sugar Grape",
    "Sprite Zero Sugar Orange",
    "Sprite Zero Sugar Peach",
    "Sprite Zero Sugar Raspberry",
    "Sprite Zero Sugar Strawberry",
    "Sprite Zero Sugar Vanilla",
    "Pibb Xtra",
    "Pibb Xtra Cherry",
    "Pibb Xtra Cherry Vanilla",
    "Pibb Xtra Strawberry",
    "Pibb Xtra Vanilla",
    "Diet Barq's Root Beer",
    "Diet Barq's Root Beer Vanilla",
    "Barq's Root Beer",
    "Barq's Root Beer Vanilla",
    "Fanta Zero Cherry",
    "Fanta Zero Fruit Punch",
    "Fanta Zero Grape",
    "Fanta Zero Lime",
    "Fanta Zero Orange",
    "Fanta Zero Peach",
    "Fanta Zero Raspberry",
    "Fanta Zero Strawberry",
    "Fanta Zero Vanilla",
    "Fanta Cherry",
    "Fanta Fruit Punch",
    "Fanta Grape",
    "Fanta Lime",
    "Fanta Orange",
    "Fanta Peach",
    "Fanta Raspberry",
    "Fanta Strawberry",
    "Pibb Zero",
    "Pibb Zero Cherry",
    "Pibb Zero Cherry Vanilla",
    "Pibb Zero Strawberry",
    "Pibb Zero Vanilla",
    "Diet Dr Pepper",
    "Diet Dr Pepper Cherry",
    "Diet Dr Pepper Cherry Vanilla",
    "Diet Dr Pepper Strawberry",
    "Diet Dr Pepper Vanilla",
    "Dr Pepper",
    "Dr Pepper Cherry",
    "Dr Pepper Cherry Vanilla",
    "Dr Pepper Strawberry",
    "Dr Pepper Vanilla",
    "Mello Yello",
    "Mello Yello Cherry",
    "Mello Yello Orange",
    "Mello Yello Peach",
    "Mello Yello Limeade",
    "Mello Yello Citrus Twist",
    "Mello Yello Raspberry Peach",
    "Mello Yello Strawberry Orange",
    "Mello Yello Zero",
    "Mello Yello Zero Cherry",
    "Mello Yello Zero Orange",
    "Mello Yello Zero Peach",
    "Mello Yello Zero Limeade",
    "Mello Yello Zero Citrus Twist",
    "Mello Yello Zero Raspberry Peach",
    "Mello Yello Zero Strawberry Orange",
    "Vitamin Water Lemonade",
    "Vitamin Water Peach Flavoured",
    "Vitamin Water Orange",
    "Vitamin Water Pink Lemonade Flavoured",
    "Vitamin Water Raspberry Flavoured",
    "Vitamin Water Strawberry Citrus Flavoured",
    "Vitamin Water Tropical Punch",
    "Fuze Iced Tea Raspberry",
    "Fuze Iced Tea Peach",
    "Fuze Iced Tea Strawberry",
    "Fuze Iced Tea Raspberry Peach",
    "Fuze Iced Tea Lemon",
    "Fuze Iced Tea Sweet",
    "Fuze Iced Tea with Lemonade",
    "Diet Fuze Iced Tea Raspberry",
    "Diet Fuze Iced Tea Lemon",
    "Diet Fuze Iced Tea Peach",
    "Diet Fuze Iced Tea Strawberry",
    "Diet Fuze Iced Tea Raspberry Peach",
    "Diet Fuze Iced Tea Sweet",
    "Fuze Iced Tea Unsweetened",
    "Diet Fuze Iced Tea with Lemonade",
    "Hi-C Cherry",
    "Hi-C Fruit Punch",
    "Hi-C Grape",
    "Hi-C Orange",
    "Hi-C Orange Vanilla",
    "Hi-C Raspberry",
    "Hi-C Raspberry Lime",
    "Hi-C Strawberry",
    "Hi-C Vanilla",
    "Seagram's Ginger Ale",
    "Seagram's Ginger Ale Cherry",
    "Seagram's Ginger Ale Lime",
    "Seagram's Ginger Ale Orange",
    "Seagram's Ginger Ale Raspberry",
    "Seagram's Ginger Ale Vanilla",
    "Seagram's Diet Ginger Ale",
    "Seagram's Diet Ginger Ale Cherry",
    "Seagram's Diet Ginger Ale Lime",
    "Seagram's Diet Ginger Ale Orange",
    "Seagram's Diet Ginger Ale Raspberry",
    "Seagram's Diet Ginger Ale Vanilla",
    "Barq's Creme Soda Peach",
    "Barq's Creme Soda Strawberry",
    "Barq's Creme Soda Vanilla",
    "Barq's Creme Soda Orange",
    "Diet Barq's Creme Soda Peach",
    "Diet Barq's Creme Soda Strawberry",
    "Diet Barq's Creme Soda Vanilla",
    "Diet Barq's Creme Soda Orange",
    "Minute Maid Sparkling Drinks Lemonade",
    "Minute Maid Sparkling Drinks Pink Lemonade",
    "Minute Maid Sparkling Drinks Mixed Berry",
    "Minute Maid Sparkling Drinks Fruit Punch",
    "Minute Maid Sparkling Drinks Strawberry Lemonade",
    "Minute Maid Sparkling Drinks Cherry Limeade",
    "Minute Maid Sparkling Drinks Limeade",
    "Minute Maid Sparkling Drinks Peach Lemonade",
    "Minute Maid Sparkling Drinks Tropical Citrus",
    "Minute Maid Lemonade",
    "Minute Maid Lemonade Cherry",
    "Minute Maid Lemonade Lemon Lime",
    "Minute Maid Lemonade Orange",
    "Minute Maid Lemonade Peach",
    "Minute Maid Lemonade Pink Lemonade",
    "Minute Maid Lemonade Raspberry",
    "Minute Maid Lemonade Strawberry",
    "Minute Maid Light Lemonade",
    "Minute Maid Light Lemonade Cherry",
    "Minute Maid Light Lemonade Lemon Lime",
    "Minute Maid Light Lemonade Orange",
    "Minute Maid Light Lemonade Peach",
    "Minute Maid Light Lemonade Pink Lemonade",
    "Minute Maid Light Lemonade Raspberry",
    "Minute Maid Light Lemonade Strawberry",
    "Powerade Zero Cherry",
    "Powerade Zero Fruit Punch",
    "Powerade Zero Grape",
    "Powerade Zero Lemon",
    "Powerade Zero Lime",
    "Powerade Zero Orange",
    "Powerade Zero Raspberry",
    "Powerade Zero Strawberry",
    "Powerade Cherry",
    "Powerade Fruit Punch",
    "Powerade Grape",
    "Powerade Lemon",
    "Powerade Lime",
    "Powerade Orange",
    "Powerade Raspberry",
    "Powerade Strawberry",
    "Minute Maid Light Drinks Fruit Punch",
    "Minute Maid Light Drinks Cherry Limeade",
    "Minute Maid Light Drinks Grape",
    "Minute Maid Light Drinks Limeade",
    "Minute Maid Light Drinks Mixed Berry",
    "Minute Maid Light Drinks Orange",
    "Minute Maid Light Drinks Peach",
    "Minute Maid Drinks Fruit Punch",
    "Minute Maid Drinks Cherry Limeade",
    "Minute Maid Drinks Grape",
    "Minute Maid Drinks Limeade",
    "Minute Maid Drinks Mixed Berry",
    "Minute Maid Drinks Orange",
    "Minute Maid Drinks Peach",
    "Dasani Cherry",
    "Dasani Grape",
    "Dasani Lemon",
    "Dasani Lime",
    "Dasani Orange",
    "Dasani Peach",
    "Dasani Raspberry",
    "Dasani Strawberry",
    "Dasani Sparkling Lemon Lime",
    "Dasani Sparkling"
]

def getRandom(arr):
    return arr[random.randint(0, len(arr)-1)]

print("""COKE FREESTYLE RANDOMIZER
by Killingyouguy

We're preparing your magical beverage...""")

total_percentage = 0
selected_sodas = []

while (total_percentage < 100):
    soda_percentage = random.randint(25, 100)
    if(soda_percentage + total_percentage > 100):
        soda_percentage = 100 - total_percentage
    total_percentage += soda_percentage
    
    soda_name = getRandom(soda)
    while(soda_name in selected_sodas):
        soda_name = getRandom(soda) # boy i wish i could just use a do-while loop
    selected_sodas.append(soda_name)

    print("{0}% of {1}".format(soda_percentage, soda_name))

print("\nEnjoy!!")
input("Press enter to exit...")



